##3 getting and cleaning data course project
# You should create one R script called run_analysis.R that does the following.
#1 Merges the training and the test sets to create one data set.
#2 Extracts only the measurements on the mean and standard deviation for each measurement.
#3 Uses descriptive activity names to name the activities in the data set
#4 Appropriately labels the data set with descriptive variable names.
#5 From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

#Q1 Merging datasets--------------------------------------------
library(data.table)
#merging data sets
subTrain <- read.table("train/subject_train.txt")
subTest <- read.table("test/subject_test.txt")
subComb <- rbind(subTrain, subTest)

xTrain <- read.table("train/X_train.txt")
xTest <- read.table("test/X_test.txt")
xComb <- rbind(xTrain, xTest)

yTrain <- read.table("train/y_train.txt")
yTest <- read.table("test/y_test.txt")
yComb <- rbind(yTrain, yTest)

combined <- cbind(subComb, yComb, xComb)
#----------------------------------------------------------------------


#Q2 Getting the datas containing mean and std--------------------------
features <- read.table("features.txt")
containMeanStd <- grep(pattern = "\\b-mean\\b|\\b-std\\b", x = features[,2])    #finding text that have -mean or -std, return the row number
xWanted <- xComb[,containMeanStd]                                               # selecting the columns in the x combined dataset
#----------------------------------------------------------------------


#Q4 Appropriately labels the data set with descriptive variable names --------------
featuresTitle <- features[containMeanStd, 2]     #getting the names
colnames(xWanted) <- featuresTitle               # setting the column names
#------------------------------------------
#combining the dataset containing mean and std with the activity name
combined2 <- cbind(subComb, yComb, xWanted)
colnames(combined2)[1] <- "person"
colnames(combined2)[2] <- "activity"
#--------------------------------------------------------------------


#Q3 merging the activity name with the activity number-----------------------
activityNames <- read.table("activity_labels.txt")
temp1 <- combined2[, 1:2]
temp2 <- merge(x = activityNames, y = temp1, by.x = "V1", by.y="activity")
combined3 <- cbind("ActivityName" = temp2[,2], combined2)
#---------------------------------------------------------------------------


#Q5calculating the mean for each person for each activity---------------
new1 <- data.table(combined3)
new7 <- aggregate(new1, by = list(new1$person, new1$activity), FUN = mean)
new8 <- merge(x = activityNames, y = new7, by.x = "V1" ,by.y = "activity") #merging the activity name, as it is taken out in the aggregate
new8$ActivityName <- new8$V2

# removing the first three columns generated by merging
new8$V1 <- NULL
new8$V2 <- NULL
new8$Group.1 <- NULL
colnames(new8)[1] <- "ActivityLabel"

#Writing the dataset for Q5 to a txt file
write.table(new8, file = "Q5.txt", row.names = FALSE)